name: Android CI

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Get version from tag
      id: tagname
      uses: JanneMattila/get-version-from-tag@v1
    - name: Use tag
      run: echo ${{steps.tagname.outputs.tag}}
    - name: Use tag
      run: echo ${{steps.tagname.outputs.version}}
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build AAR
      run: bash ./gradlew :Samplesdk:assemble
    - name: Upload aar
      uses: actions/upload-artifact@v2.2.4
      with:
        name: aar archive $GIT_TAG_NAME
        path: Samplesdk/build/outputs/aar/rikesh.aar
    - name: upload readme.txt
      uses: actions/upload-artifact@v2.2.4
      with:
        name: aar archive
        path: Readme.txt
    - name: upload config.txt
      uses: actions/upload-artifact@v2.2.4
      with:
        name: aar archive
        path: Config.txt
    - name: upload assest file
      uses: actions/upload-artifact@v2.2.4
      with:
        name: aar archive
        path: app/src/main/assets/aa.txt
       
    
      

